/*
========================================================================================
STORED PROCEDURE: LOAD BRONZE LAYER (SOURCE => BRONZE)
========================================================================================
SCRIPT PURPOSE:
  THIS STORED PROCEDURE LOADS DATA INTO THE 'BRONZE' SCHEMA FROM EXTERNAL CSN FILES.
  IT PERFORMS THE FOLLOWING ACTIONS:
  - TRUNCATES THE BRONZE TABLES BEFORE LOADING DATA.
  - USES THE 'BULK INSERT' COMMAND TO LOAD DATA FROM CSV FILES TO BRONZE TABLES.

PARAMETERS:
  NONE.
THIS STORED PROCEDURE DOES NOT ACCEPT ANY PARAMETERS OR RETURN ANY VALUES.

USAGE EXAMPLE:
  EXEC BRONZE.LOAD_BRONZE;
========================================================================================
*/

-- ALL STORED PROCEDURES USED FOR LOADING DATA MUST FOLLOW THE NAMING PATTERN AS 
-- LOAD_<LAYER> WHERE LAYER = BRONZE, SILVER OR GOLD

CREATE OR ALTER PROCEDURE BRONZE.LOAD_BRONZE AS
BEGIN
	DECLARE @START_TIME DATETIME, @END_TIME DATETIME, @BATCH_START_TIME DATETIME, @BATCH_END_TIME DATETIME;
	BEGIN TRY
		SET @BATCH_START_TIME = GETDATE();
		PRINT '====================================================================';
		PRINT 'LOADING BRONZE LAYER';
		PRINT '====================================================================';

		PRINT '--------------------------------------------------------------------';
		PRINT 'LOADING THE CRM TABLES';
		PRINT '--------------------------------------------------------------------';

		SET @START_TIME = GETDATE();
		PRINT '>> TRUNCATING TABLE: BRONZE.CRM_CUST_INFO';
		TRUNCATE TABLE BRONZE.CRM_CUST_INFO; 
	
		PRINT '>> INSERTING TABLE: BRONZE.CRM_CUST_INFO';
		BULK INSERT BRONZE.CRM_CUST_INFO
		FROM 'D:\WAREHOUSE\dataset\source_crm\cust_info.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @END_TIME = GETDATE();
		PRINT '>> LOAD DURATION:' + CAST(DATEDIFF (SECOND, @START_TIME, @END_TIME) AS NVARCHAR) + 'SECONDS';
		PRINT '>> -----------------------';

		SET @START_TIME = GETDATE();
		PRINT '>> TRUNCATING TABLE: BRONZE.CRM_PRD_INFO';
		TRUNCATE TABLE BRONZE.CRM_PRD_INFO; 

		PRINT '>> INSERTING TABLE: BRONZE.CRM_PRD_INFO';
		BULK INSERT BRONZE.CRM_PRD_INFO
		FROM 'D:\WAREHOUSE\dataset\source_crm\prd_info.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @END_TIME = GETDATE();
		PRINT '>> LOAD DURATION:' + CAST(DATEDIFF (SECOND, @START_TIME, @END_TIME) AS NVARCHAR) + 'SECONDS';
		PRINT '>> -----------------------';

		SET @START_TIME = GETDATE();
		PRINT '>> TRUNCATING TABLE: BRONZE.CRM_SALES_DETAILS';
		TRUNCATE TABLE BRONZE.CRM_SALES_DETAILS; 

		PRINT '>> INSERTING TABLE: BRONZE.CRM_SALES_DETAILS';
		BULK INSERT BRONZE.CRM_SALES_DETAILS
		FROM 'D:\WAREHOUSE\dataset\source_crm\sales_details.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @END_TIME = GETDATE();
		PRINT '>> LOAD DURATION:' + CAST(DATEDIFF (SECOND, @START_TIME, @END_TIME) AS NVARCHAR) + 'SECONDS';
		PRINT '>> -----------------------';

		PRINT '--------------------------------------------------------------------';
		PRINT 'LOADING THE ERP TABLES';
		PRINT '--------------------------------------------------------------------';

		SET @START_TIME = GETDATE();
		PRINT '>> TRUNCATING TABLE: BRONZE.ERP_CUST_AZ12';
		TRUNCATE TABLE BRONZE.ERP_CUST_AZ12; 

		PRINT '>> INSERTING TABLE: BRONZE.ERP_CUST_AZ12';
		BULK INSERT BRONZE.ERP_CUST_AZ12
		FROM 'D:\WAREHOUSE\dataset\source_erp\CUST_AZ12.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @END_TIME = GETDATE();
		PRINT '>> LOAD DURATION:' + CAST(DATEDIFF (SECOND, @START_TIME, @END_TIME) AS NVARCHAR) + 'SECONDS';
		PRINT '>> -----------------------';

		SET @START_TIME = GETDATE();
		PRINT '>> TRUNCATING TABLE: BRONZE.ERP_LOC_A101';
		TRUNCATE TABLE BRONZE.ERP_LOC_A101; 

		PRINT '>> INSERTING TABLE: BRONZE.ERP_LOC_A101';
		BULK INSERT BRONZE.ERP_LOC_A101
		FROM 'D:\WAREHOUSE\dataset\source_erp\LOC_A101.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @END_TIME = GETDATE();
		PRINT '>> LOAD DURATION:' + CAST(DATEDIFF (SECOND, @START_TIME, @END_TIME) AS NVARCHAR) + 'SECONDS';
		PRINT '>> -----------------------';

		SET @START_TIME = GETDATE();
		PRINT '>> TRUNCATING TABLE: BRONZE.ERP_PX_CAT_G1V2';
		TRUNCATE TABLE BRONZE.ERP_PX_CAT_G1V2; 

		PRINT '>> INSERTING TABLE: BRONZE.ERP_PX_CAT_G1V2';
		BULK INSERT BRONZE.ERP_PX_CAT_G1V2
		FROM 'D:\WAREHOUSE\dataset\source_erp\PX_CAT_G1V2.csv'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = ',',
			TABLOCK
		);
		SET @END_TIME = GETDATE();
		PRINT '>> LOAD DURATION:' + CAST(DATEDIFF (SECOND, @START_TIME, @END_TIME) AS NVARCHAR) + 'SECONDS';
		PRINT '>> -----------------------';

		SET @BATCH_END_TIME = GETDATE();
		PRINT '====================================================================';
		PRINT '>> LOADING BRONZE LAYER IS COMPLETED';
		PRINT 'TOTAL BATCH LOAD DURATION: ' + CAST (DATEDIFF (SECOND, @BATCH_START_TIME, @BATCH_END_TIME) AS NVARCHAR) + 'SECONDS';
		PRINT '====================================================================';
	END TRY
	BEGIN CATCH
	-- TRACK ETL DURATION => HELPS TO IDENTIFY BOTTLENECKS, OPTIMIZE PERFORMANCE, MONITOR TRENDS, DETECT ISSUES
		PRINT '====================================================================';
		PRINT ' ERROR OCCURED DURING LOADING BRONZE LAYER'
		PRINT 'ERROR MESSAGE' + ERROR_MESSAGE();
		PRINT 'ERROR MESSAGE' + CAST (ERROR_NUMBER() AS NVARCHAR);
		PRINT 'ERROR MESSAGE' + CAST (ERROR_STATE() AS NVARCHAR);
		PRINT '====================================================================';
	END CATCH
END;
