/*
--===========================================================================================================
QUALITY CHECKS
--===========================================================================================================
SCRIPT PURPOSE:
  THIS SCRIPT PERFROMS VARIOUS QUALITY CHECKS FOR TO VALIDATE INTEGRITY, CONSISTENCY, AND ACCURACY
  OF THE GOLD LAYER. IT INCLUDES CHECKS FOR:
  - UNIQUENESS OF SURROGATE KEYS IN DIMENAION TABLES.
  - REFERENTIAL INTEGRITY BETWEEN FACT AND DIMENSION TABLES.
  - VALIDATION OF RELATIONSHIPS IN THE DATA MODEL FOR ANALYTICAL PURPOSES.

  USAGE NOTES:
  - RUN THESE CHECKS AFTER DATA LOADING SILVER LAYER.
  - INVESTIGATE AND RESOLVE ANY DISCREPANCIES FOUND DURING THE CHECKS.
--===========================================================================================================
*/

--=============================================================================
-- CHECKING FOR 'GOLD.DIM_CUSTOMERS
--=============================================================================

-- TO CHECK THE UNIQUENESS OF THE CST_ID
SELECT CST_ID, COUNT(*) 
FROM(
	SELECT
		CI.CST_ID,
		CI.CST_KEY,
		CI.CST_FIRSTNAME,
		CI.CST_LASTNAME,
		CI.CST_MARITAL_STATUS,
		CI.CST_GNDR,
		CI.CST_CREATE_DATE,
		CA.BDATE,
		CA.GEN,
		LA.CNTRY
	FROM SILVER.CRM_CUST_INFO CI
	LEFT JOIN SILVER.ERP_CUST_AZ12 CA
	ON CI.CST_KEY = CA.CID
	LEFT JOIN SILVER.ERP_LOC_A101 LA
	ON  CI.CST_KEY = LA.CID
)T GROUP BY CST_ID
HAVING COUNT(*)>1;

-- DATA INTEGRATION
SELECT DISTINCT
	CI.CST_GNDR,
	CA.GEN,
	CASE
		WHEN CI.CST_GNDR != 'N/A' THEN CI.CST_GNDR
		ELSE ISNULL(CA.GEN, 'N/A')
	END AS NEW_GNDR
FROM SILVER.CRM_CUST_INFO CI
LEFT JOIN SILVER.ERP_CUST_AZ12 CA
ON CI.CST_KEY = CA.CID
LEFT JOIN SILVER.ERP_LOC_A101 LA
ON  CI.CST_KEY = LA.CID
ORDER BY CI.CST_GNDR, CA.GEN;

--=============================================================================
-- CHECKING FOR 'GOLD.DIM_PRODUCT
--=============================================================================

-- to check uniqueness of prd_key
SELECT PRD_KEY, COUNT(*) 
FROM(
	SELECT
		PN.PRD_ID,
		PN.CAT_ID,
		PN.PRD_KEY,
		PN.PRD_NM,
		PN.PRD_COST,
		PN.PRD_LINE,
		PN.PRD_START_DT,
		PC.CAT,
		PC.SUBCAT,
		PC.MAINTENANCE
	FROM SILVER.CRM_PRD_INFO PN
	LEFT JOIN SILVER.ERP_PX_CAT_G1V2 PC
	ON PN.CAT_ID = PC.ID
	WHERE PN.PRD_END_DT IS NULL -- FILER OUT ALL HISTORICAL DATA
)T GROUP BY PRD_KEY
HAVING COUNT(*)>1;

SELECT
	PN.PRD_ID,
	PN.PRD_KEY,
	PN.PRD_NM,
	PN.CAT_ID,
	PC.CAT,
	PC.SUBCAT,
	PC.MAINTENANCE,
	PN.PRD_COST,
	PN.PRD_LINE,
	PN.PRD_START_DT
FROM SILVER.CRM_PRD_INFO PN
LEFT JOIN SILVER.ERP_PX_CAT_G1V2 PC
ON PN.CAT_ID = PC.ID
WHERE PN.PRD_END_DT IS NULL -- FILER OUT ALL HISTORICAL DATA

SELECT
*
FROM SILVER.CRM_PRD_INFO;

SELECT
*
FROM SILVER.ERP_PX_CAT_G1V2;

--=============================================================================
-- CHECKING FOR 'GOLD.FACT_SALES
--=============================================================================

-- USE THE DIMENSION'S SURROGATE KEYS INSTEAD OF IDS TO EASILY CONNECT FACTS WITH DIMENSIONS
SELECT
	DM.CUSTOMER_KEY,
	DP.PRODUCT_KEY,
	SD.SLS_ORD_NUM,
	SD.SLS_PRD_KEY,
	SD.SLS_CUST_ID,
	SD.SLS_ORDER_DT,
	SD.SLS_SHIP_DT,
	SD.SLS_DUE_DT,
	SD.SLS_SALES,
	SD.SLS_QUANTITY,
	SD.SLS_PRICE
FROM SILVER.CRM_SALES_DETAILS SD
LEFT JOIN GOLD.DIM_CUSTOMERS DM
ON SD.SLS_CUST_ID = DM.CUSTOMER_ID
LEFT JOIN GOLD.DIM_PRODUCT DP
ON SD.SLS_PRD_KEY = DP.PRODUCT_ID;

SELECT
*
FROM GOLD.DIM_CUSTOMERS;

SELECT
*
FROM GOLD.DIM_PRODUCT;
