/*
=====================================================================================
CREATE DATABASE AND SCHEMAS
=====================================================================================
SCRIPT PURPOSE:
  THIS SCRIPT CREATES A NEW DATABASE NAMED 'DATAWAREHOUSE' AFTER CHECKING IF IT ALREADY EXISTS.
  IF THE DATABASE EXISTS, IT IS DROPPED AND RECREATED. ADDITIONALLY, THE SCRIPT SETS UP THREE SCHEMAS
  WITHIN THE DATABASE: 'BRONZE', 'SILVER', AND 'GOLD'.

WARNING:
  RUNNING THIS SCRIPT WILL DROP THE ENTIRE 'DATAWAREHOUSE' DATABASE IF IT EXISTS.
  ALL DATA IN THE DATABASE WILL BE PERMANENTLY DELETED. PROCEED WITH CAUTION 
  AND ENSURE YOU HAVE PROPER BACKUPS BEFORE RUNNING THIS SCRIPT.
*/

USE MASTER;
GO

-- DROP AND REACREATE THE 'DATAWAREHOUSE' DATABASE
IF EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME = 'DATAWAREHOUSE')
BEGIN
  ALTER DATABASE DATAWAREHOUSE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE DATAWAREHOUSE;
END;
GO

-- create the 'DATAWAREHOUSE' database
CREATE DATABASE DATAWAREHOUSE;
USE DATAWAREHOUSE;

CREATE SCHEMA BRONZE;
GO
CREATE SCHEMA SILVER;
GO
CREATE SCHEMA GOLD;
GO
