/*
==============================================================================
DDL SCRIPT: CREATE GOLD TABLES
==============================================================================
SCRIPT PURPOSE:
  THIS SCRIPT CREATES VIEWS IN THE 'GOLD' LAYER IN THE DATA WAREHOUSE.
  THE GOLD LAYER REPRESENTS THE FINAL DIMENSION AND FACT TABLES (STAR SCHEMA)

  EACH VIEW PERFORMS TRANSFORMATIONS AND COMBINES DATA FROM THE SILVER LAYER
  TO PRODUCE A CLEAN, ENRICHED, AND BUSINESS-READY DATASET.

  USAGE:
    - THESE VIEWS CAN BE QUERIED DIRECTLY FOR ANALYTICS AND REPORTING.
==============================================================================
*/

--customers
--===================================================================================
-- CREATE DIMENSION TABLE: GOLD.DIM_CUSTOMERS
--===================================================================================

IF OBJECT_ID('GOLD.DIM_CUSTOMERS', 'V') IS NOT NULL
	DROP VIEW GOLD.DIM_CUSTOMERS;
GO

CREATE VIEW GOLD.DIM_CUSTOMERS AS(
SELECT 
	ROW_NUMBER() OVER(ORDER BY CST_ID) AS CUSTOMER_KEY,
	CI.CST_ID AS CUSTOMER_ID,
	CI.CST_KEY AS CUSTOMER_NUMBER,
	CI.CST_FIRSTNAME AS FIRST_NAME,
	CI.CST_LASTNAME AS LAST_NAME,
	LA.CNTRY AS COUNTRY,
	CI.CST_MARITAL_STATUS AS MARITAL_STATUS,
	CASE
		WHEN CI.CST_GNDR != 'N/A' THEN CI.CST_GNDR -- CRM IS THE MASTER FOR GENDER
		ELSE ISNULL(CA.GEN, 'N/A')
	END AS GENDER,
	CA.BDATE AS BIRTHDATE,
	CI.CST_CREATE_DATE AS CREATE_DATE
FROM SILVER.CRM_CUST_INFO CI
LEFT JOIN SILVER.ERP_CUST_AZ12 CA
ON CI.CST_KEY = CA.CID
LEFT JOIN SILVER.ERP_LOC_A101 LA
ON  CI.CST_KEY = LA.CID
);

SELECT
*
FROM GOLD.DIM_CUSTOMERS;

--products
--===================================================================================
-- CREATE DIMENSION TABLE: GOLD.DIM_PRODUCT
--===================================================================================

IF OBJECT_ID('GOLD.DIM_PRODUCT', 'V') IS NOT NULL
	DROP VIEW GOLD.DIM_PRODUCT;
GO

CREATE VIEW GOLD.DIM_PRODUCT AS(
SELECT
	ROW_NUMBER() OVER(ORDER BY PRD_START_DT) AS PRODUCT_KEY,
	PN.PRD_ID AS PRODUCT_ID,
	PN.PRD_KEY AS PRODUCT_NUMBER,
	PN.PRD_NM AS PRODUCT_NAME,
	PN.CAT_ID AS CATEGORY_ID,
	PC.CAT AS CATEGORY,
	PC.SUBCAT AS SUBCATEGORY,
	PC.MAINTENANCE,
	PN.PRD_COST AS COST,
	PN.PRD_LINE AS PRODUCT_LINE,
	PN.PRD_START_DT AS START_DATE
FROM SILVER.CRM_PRD_INFO PN
LEFT JOIN SILVER.ERP_PX_CAT_G1V2 PC
ON PN.CAT_ID = PC.ID
WHERE PN.PRD_END_DT IS NULL -- FILER OUT ALL HISTORICAL DATA
);

SELECT
*
FROM GOLD.DIM_PRODUCT;

--sales
--===================================================================================
-- CREATE DIMENSION TABLE: GOLD.FACT_SALES
--===================================================================================

IF OBJECT_ID('GOLD.FACT_SALES', 'V') IS NOT NULL
	DROP VIEW GOLD.FACT_SALES;
GO

CREATE VIEW GOLD.FACT_SALES AS
SELECT
	SD.SLS_ORD_NUM AS ORDER_NUMBER,
	DM.CUSTOMER_KEY,
	DP.PRODUCT_KEY,
	SD.SLS_ORDER_DT AS ORDER_DATE,
	SD.SLS_SHIP_DT AS SHIPPING_DATE,
	SD.SLS_DUE_DT AS DUE_DATE,
	SD.SLS_SALES AS SALES,
	SD.SLS_QUANTITY AS QUANTITY,
	SD.SLS_PRICE AS PRICE
FROM SILVER.CRM_SALES_DETAILS SD
LEFT JOIN GOLD.DIM_CUSTOMERS DM
ON SD.SLS_CUST_ID = DM.CUSTOMER_ID
LEFT JOIN GOLD.DIM_PRODUCT DP
ON SD.SLS_PRD_KEY = DP.PRODUCT_NUMBER;

SELECT
*
FROM GOLD.FACT_SALES;
